### ISSUE TITLE
Optional: padding in the button

### ISSUE THREAD

**Issue by rudnitskih** [JukaChu/candys_landing2#4]
![image](https://user-images.githubusercontent.com/8848858/55654088-16a69580-57f9-11e9-87b0-4a1bf48297e0.png)

Maybe is related only to mac

**Comment by JukaChu** [comment]
maybe.  

 ![image](https://user-images.githubusercontent.com/48647343/55689262-0f16f600-598b-11e9-8157-5c04717fab23.png) 
what i told on our lesson, text after logo (site + pixel extansion).  idk what is it

**Comment by rudnitskih** [comment]
Show me on the lesson please will check
